<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_concat(Corporate Company, , s Batch Fee_304833</name>
   <tag></tag>
   <elementGuidId>1b4637c2-befb-43c5-a80e-3277dd4dc158</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-large.size-large.wp-image-7533</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[2]/div/div/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>94a713d8-af4d-4328-a6d2-a754fc04cbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>148dd645-d72f-41e1-8d57-8eb7c9ca152d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>565b0903-6b9c-4130-a590-29139903b532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1024</value>
      <webElementGuid>61a28906-52a3-49dc-ad96-7e120eca2bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>428</value>
      <webElementGuid>d16d3982-06cf-462b-9d71-1bd9f1e516a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://nxtgenaiacademy.com/wp-content/uploads/2023/07/1-min-1024x428.jpg</value>
      <webElementGuid>406139e4-4d9b-4580-b047-e957cdb22f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-large size-large wp-image-7533</value>
      <webElementGuid>5e9fd3de-468e-42c2-84f8-c25d9240fec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://nxtgenaiacademy.com/wp-content/uploads/2023/07/1-min-1024x428.jpg 1024w, https://nxtgenaiacademy.com/wp-content/uploads/2023/07/1-min-300x125.jpg 300w, https://nxtgenaiacademy.com/wp-content/uploads/2023/07/1-min-768x321.jpg 768w, https://nxtgenaiacademy.com/wp-content/uploads/2023/07/1-min.jpg 1241w</value>
      <webElementGuid>ef929bff-36e0-457b-9212-0ec0b450f720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 1024px) 100vw, 1024px</value>
      <webElementGuid>c398eeed-9d71-4aa4-83eb-e6a8ee265cb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;post_type_exist clearfix&quot;]/div[@class=&quot;elementor elementor-32&quot;]/div[@class=&quot;elementor-element elementor-element-3bfa065 e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-5b031eb elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/img[@class=&quot;attachment-large size-large wp-image-7533&quot;]</value>
      <webElementGuid>81fcd712-0ddd-464e-9add-602e1a51c353</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/div/div/div/div/div/div/img</value>
      <webElementGuid>cfe0de31-e836-4bd2-acc2-fcb6381cef01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://nxtgenaiacademy.com/wp-content/uploads/2023/07/1-min-1024x428.jpg')]</value>
      <webElementGuid>d94491b0-763d-48de-a451-7164b33202cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>e52d0ceb-953f-434f-8e5c-e090cde3cc42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://nxtgenaiacademy.com/wp-content/uploads/2023/07/1-min-1024x428.jpg']</value>
      <webElementGuid>e8a52d06-1eb8-4dbb-bfa9-939059c9efcf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
