<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Download Course Brochure_attachment-lar_4fd380</name>
   <tag></tag>
   <elementGuidId>c8805df8-704e-4f6d-8238-0066e0e5c20a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.attachment-large.size-large.wp-image-7463</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div[2]/div/div/div/div/div[3]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dde2711b-3e23-4561-9141-5f4e31135a89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>bdf4687c-4ad8-44b0-9ee8-7bb16eb994ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>700bf7ba-aa1c-4b3a-ae91-ae95bef5b2e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1024</value>
      <webElementGuid>33efcbc9-ad62-453c-9897-c5fe14fe8247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>558</value>
      <webElementGuid>8410fe12-575e-4bda-ac8a-cba58c1e5a6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://vinothqaacademy.com/wp-content/uploads/2023/05/Roapmap-1024x558.png</value>
      <webElementGuid>917cc631-2b4c-4b3c-ab35-7bebb45106c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>attachment-large size-large wp-image-7463</value>
      <webElementGuid>d3e766e5-f6d9-4cda-935c-c1472021ec64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>https://vinothqaacademy.com/wp-content/uploads/2023/05/Roapmap-1024x558.png 1024w, https://vinothqaacademy.com/wp-content/uploads/2023/05/Roapmap-300x163.png 300w, https://vinothqaacademy.com/wp-content/uploads/2023/05/Roapmap-768x418.png 768w, https://vinothqaacademy.com/wp-content/uploads/2023/05/Roapmap-1536x836.png 1536w, https://vinothqaacademy.com/wp-content/uploads/2023/05/Roapmap.png 2000w</value>
      <webElementGuid>bca7e5af-e2f3-43f3-909f-d95b1480ea6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>(max-width: 1024px) 100vw, 1024px</value>
      <webElementGuid>8327cade-38b5-4075-9f0b-a119f984af1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;post_type_exist clearfix&quot;]/div[@class=&quot;elementor elementor-6248&quot;]/div[@class=&quot;elementor-element elementor-element-6c4ac88e e-flex e-con-boxed e-con e-parent&quot;]/div[@class=&quot;e-con-inner&quot;]/div[@class=&quot;elementor-element elementor-element-68a128f elementor-widget elementor-widget-image&quot;]/div[@class=&quot;elementor-widget-container&quot;]/img[@class=&quot;attachment-large size-large wp-image-7463&quot;]</value>
      <webElementGuid>c750cd92-f13a-4379-a5e0-a128c56de4e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div[2]/div/div/div/div/div[3]/div/img</value>
      <webElementGuid>785667fd-cc28-419a-b14e-b4fe469cfd3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://vinothqaacademy.com/wp-content/uploads/2023/05/Roapmap-1024x558.png')]</value>
      <webElementGuid>52919f94-e4c2-4eb7-8aea-1ab43bdc4fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>d3b98a40-3d80-4971-bbd1-f779dc726423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://vinothqaacademy.com/wp-content/uploads/2023/05/Roapmap-1024x558.png']</value>
      <webElementGuid>79ede004-8e7a-4147-aef9-cbe987734bc4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
