<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>canvas_Today_3nQG24E5</name>
   <tag></tag>
   <elementGuidId>0483704d-14db-4155-a570-7909c785d20d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//canvas[@id='3nQG24E5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#3nQG24E5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>canvas</value>
      <webElementGuid>c6cc6565-97ca-4f6c-8587-71e9f25548eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>3nQG24E5</value>
      <webElementGuid>7ee8a982-44e7-49c4-a0f9-f4ee11dc9af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>415</value>
      <webElementGuid>9fa67e1e-6573-46ff-ac58-1447bb88ebd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>397</value>
      <webElementGuid>7a69e27c-3630-4335-820e-321ce1aa9e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;3nQG24E5&quot;)</value>
      <webElementGuid>e2d93a83-0cc2-4abe-908d-ba0d9bb29d2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//canvas[@id='3nQG24E5']</value>
      <webElementGuid>2edf7f8c-3b78-4d9a-bd5d-cbef9c8746b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div[6]/div/div[2]/div/div/canvas</value>
      <webElementGuid>61b5b769-8156-460f-bdbb-8d85170e52ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/canvas</value>
      <webElementGuid>1f5e33eb-5b36-4e12-bf68-ab7b16803886</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//canvas[@id = '3nQG24E5']</value>
      <webElementGuid>f7b1e6a5-6bd9-4443-823c-3db9f61b8d4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
