<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Punched OutPunched Out Today at 1023 AM_d731f4</name>
   <tag></tag>
   <elementGuidId>6e998bb9-17ae-4f51-a210-9a1b6f94c65b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-dashboard-widget-body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6c56543f-4a3c-41b7-81d7-3f6c2289f492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-dashboard-widget-body</value>
      <webElementGuid>e0ccb68e-ea56-4fec-aa76-b4a93bfa831e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Punched OutPunched Out: Today at 10:23 AM (GMT 5.5)9h 33m TodayThis WeekNov 13 - Nov 1981h 33m </value>
      <webElementGuid>882f111b-6836-44d8-bc1d-793f09b93c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;oxd-grid-3 orangehrm-dashboard-grid&quot;]/div[@class=&quot;oxd-grid-item oxd-grid-item--gutters orangehrm-dashboard-widget&quot;]/div[@class=&quot;oxd-sheet oxd-sheet--rounded oxd-sheet--white orangehrm-dashboard-widget&quot;]/div[@class=&quot;orangehrm-dashboard-widget-body&quot;]</value>
      <webElementGuid>bf7746c7-442f-45ba-b7dc-dcdcdffa2ae5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div/div/div[2]</value>
      <webElementGuid>b0ce7cbf-8c45-4ecd-88f9-cb440902619e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[2]</value>
      <webElementGuid>87f99baa-2e34-45ab-be2e-f8b476b3702e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Punched OutPunched Out: Today at 10:23 AM (GMT 5.5)9h 33m TodayThis WeekNov 13 - Nov 1981h 33m ' or . = 'Punched OutPunched Out: Today at 10:23 AM (GMT 5.5)9h 33m TodayThis WeekNov 13 - Nov 1981h 33m ')]</value>
      <webElementGuid>1c0fca1d-7dc9-4e45-9b4f-3a734b320e74</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
