<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Employee ClaimsEmployee NameReference I_cbf2a3</name>
   <tag></tag>
   <elementGuidId>6b181bd4-e06e-48a8-a1de-9016cfe2e083</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.oxd-table-filter</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5dd03beb-5612-4ef3-a145-2031e9ef1b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-table-filter</value>
      <webElementGuid>0082a8c1-eae1-4ffe-a5e0-502d5c6652f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Employee ClaimsEmployee NameReference IdEvent Name-- Select --Status-- Select --From DateTo DateIncludeCurrent Employees Only Reset  Search </value>
      <webElementGuid>b7062145-cb28-4261-bd7c-bbe96e049556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;oxd-table-filter&quot;]</value>
      <webElementGuid>a00b5254-6414-4892-a69f-7b1f117ec1da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div</value>
      <webElementGuid>d5e4db06-a42d-4777-ba3f-68720e7f74db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configuration'])[1]/following::div[5]</value>
      <webElementGuid>5c18bee4-aa49-428a-afbc-6ee68b97d1fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>b2e1bcf5-e926-4417-b66e-71920b0c8131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Employee ClaimsEmployee NameReference IdEvent Name-- Select --Status-- Select --From DateTo DateIncludeCurrent Employees Only Reset  Search ' or . = 'Employee ClaimsEmployee NameReference IdEvent Name-- Select --Status-- Select --From DateTo DateIncludeCurrent Employees Only Reset  Search ')]</value>
      <webElementGuid>a7635ad2-32f3-47a9-8fb2-d8bc65ab6c08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
