<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_VacanciesJob Title-- Select --Vacancy--_ae64d7</name>
   <tag></tag>
   <elementGuidId>83248f39-08c6-4fb9-875e-81415a7d76b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-background-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>db9eb6f4-5647-499c-898f-499c042fcf38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-background-container</value>
      <webElementGuid>4080e868-eaac-45bd-b071-0fc5678600bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VacanciesJob Title-- Select --Vacancy-- Select --Hiring Manager-- Select --Status-- Select -- Reset  Search  Add  (7) Records FoundVacancyAscendingDescendingJob TitleAscendingDescendingHiring ManagerAscendingDescendingStatusAscendingDescendingActionsAssociate IT ManagerIT Manager (Deleted)ActiveJunior Account AssistantAccount Assistant (Deleted)ActivePayroll AdministratorPayroll AdministratorOpgMwsofSg KumarkumarActiveSales RepresentativeSales Representative (Deleted)ActiveSenior QA LeadQA Lead (Deleted)ActiveSenior Support SpecialistSupport Specialist (Deleted)ActiveSoftware EngineerSoftware Engineer (Deleted)Active</value>
      <webElementGuid>10967f90-d4c6-44a3-a0e3-60c6d8550e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]</value>
      <webElementGuid>374f2008-b3af-4ae7-b5f6-7c6044a634ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div</value>
      <webElementGuid>ce181614-99e6-4146-b9ec-05cbeeaa95a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>0b591170-87b8-4de4-a0a4-9fca37695e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'VacanciesJob Title-- Select --Vacancy-- Select --Hiring Manager-- Select --Status-- Select -- Reset  Search  Add  (7) Records FoundVacancyAscendingDescendingJob TitleAscendingDescendingHiring ManagerAscendingDescendingStatusAscendingDescendingActionsAssociate IT ManagerIT Manager (Deleted)ActiveJunior Account AssistantAccount Assistant (Deleted)ActivePayroll AdministratorPayroll AdministratorOpgMwsofSg KumarkumarActiveSales RepresentativeSales Representative (Deleted)ActiveSenior QA LeadQA Lead (Deleted)ActiveSenior Support SpecialistSupport Specialist (Deleted)ActiveSoftware EngineerSoftware Engineer (Deleted)Active' or . = 'VacanciesJob Title-- Select --Vacancy-- Select --Hiring Manager-- Select --Status-- Select -- Reset  Search  Add  (7) Records FoundVacancyAscendingDescendingJob TitleAscendingDescendingHiring ManagerAscendingDescendingStatusAscendingDescendingActionsAssociate IT ManagerIT Manager (Deleted)ActiveJunior Account AssistantAccount Assistant (Deleted)ActivePayroll AdministratorPayroll AdministratorOpgMwsofSg KumarkumarActiveSales RepresentativeSales Representative (Deleted)ActiveSenior QA LeadQA Lead (Deleted)ActiveSenior Support SpecialistSupport Specialist (Deleted)ActiveSoftware EngineerSoftware Engineer (Deleted)Active')]</value>
      <webElementGuid>388b842d-6834-4899-90a1-cb531efa41c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
