<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LocationsNameCityCountry-- Select -- Re_af730f</name>
   <tag></tag>
   <elementGuidId>462f329a-37a7-4b48-800e-f6b11311e5f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-background-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a0197c33-dc1b-4652-a7d3-2dd087b79b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-background-container</value>
      <webElementGuid>c19be624-064c-432c-a818-20698022fee8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LocationsNameCityCountry-- Select -- Reset  Search  Add  (4) Records FoundNameAscendingDescendingCityAscendingDescendingCountryAscendingDescendingPhoneAscendingDescendingNumber of EmployeesAscendingDescendingActionsCanadian Regional HQOttawaCanada1-876-267-69990HQ - CA, USACaliforniaUnited States1-888-452-15080New York Sales OfficeNew YorkUnited States1 (866) 781-71040Texas R&amp;DTexasUnited States1 (866) 791-72041</value>
      <webElementGuid>8812f40b-e032-4695-a862-69868ed2bbd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]</value>
      <webElementGuid>76a968a9-83fa-4346-a451-c2dcb71ae1ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div</value>
      <webElementGuid>036a3679-8d06-4dd6-a045-55c16f7de388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More'])[1]/following::div[5]</value>
      <webElementGuid>77cbefd2-687a-4470-90e1-77471a8b4aea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qualifications'])[1]/following::div[5]</value>
      <webElementGuid>1182b8ba-0606-416e-a6e8-9a7e8c5ad825</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div</value>
      <webElementGuid>b3cb631f-7bb0-42c3-a151-daf9dc420e62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'LocationsNameCityCountry-- Select -- Reset  Search  Add  (4) Records FoundNameAscendingDescendingCityAscendingDescendingCountryAscendingDescendingPhoneAscendingDescendingNumber of EmployeesAscendingDescendingActionsCanadian Regional HQOttawaCanada1-876-267-69990HQ - CA, USACaliforniaUnited States1-888-452-15080New York Sales OfficeNew YorkUnited States1 (866) 781-71040Texas R&amp;DTexasUnited States1 (866) 791-72041' or . = 'LocationsNameCityCountry-- Select -- Reset  Search  Add  (4) Records FoundNameAscendingDescendingCityAscendingDescendingCountryAscendingDescendingPhoneAscendingDescendingNumber of EmployeesAscendingDescendingActionsCanadian Regional HQOttawaCanada1-876-267-69990HQ - CA, USACaliforniaUnited States1-888-452-15080New York Sales OfficeNew YorkUnited States1 (866) 781-71040Texas R&amp;DTexasUnited States1 (866) 791-72041')]</value>
      <webElementGuid>b80603e7-6102-4822-928a-4989ecc6c387</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
