<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_100 AdministrationEngineeringSales  Mar_2e74d5</name>
   <tag></tag>
   <elementGuidId>17f255a1-c9bc-43dd-9b1b-0dc09c23eb49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.org-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>86a75128-1db2-4e1d-8295-000b759b0578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>org-container</value>
      <webElementGuid>f4dfde39-a999-4544-b569-eb64f83eff4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100: AdministrationEngineeringSales &amp; MarketingClient ServicesFinanceHuman Resources1: holajuan perez</value>
      <webElementGuid>9a66da85-7b64-49b7-be29-3b5fba16e480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-paper-container&quot;]/div[@class=&quot;org-container&quot;]</value>
      <webElementGuid>955a5289-640b-416b-9403-ebe0ca29871b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div/div[3]</value>
      <webElementGuid>84a6ecd6-a8f7-4280-a000-a1fb19d87d81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]</value>
      <webElementGuid>15dc323c-3166-404e-acdb-174be9e32e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '100: AdministrationEngineeringSales &amp; MarketingClient ServicesFinanceHuman Resources1: holajuan perez' or . = '100: AdministrationEngineeringSales &amp; MarketingClient ServicesFinanceHuman Resources1: holajuan perez')]</value>
      <webElementGuid>ef476967-a0fd-4155-a635-a9e5d4f5a6c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
