<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_MembershipActionsACCAAdministracjaBriti_0d9322</name>
   <tag></tag>
   <elementGuidId>ad50a381-096c-4a02-86bd-2b0a69aaf7be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bbed26f2-e414-4848-8dbe-6ca1c790d855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-container</value>
      <webElementGuid>10e6a68c-0a54-47ca-84aa-ee5546f3f6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MembershipActionsACCAAdministracjaBritish Computer Society (BCS)Chartered Institute of Marketing (CIM)CIMA</value>
      <webElementGuid>96550ed6-6375-45bd-bdc3-3e2c3249d7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-paper-container&quot;]/div[@class=&quot;orangehrm-container&quot;]</value>
      <webElementGuid>fb5b37aa-7e49-4651-8254-5e6667579f6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div/div[3]</value>
      <webElementGuid>7d681272-9aa2-432c-94e4-8297c18a2d0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]</value>
      <webElementGuid>88b507f2-701d-427e-ba9f-ce933c78d372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'MembershipActionsACCAAdministracjaBritish Computer Society (BCS)Chartered Institute of Marketing (CIM)CIMA' or . = 'MembershipActionsACCAAdministracjaBritish Computer Society (BCS)Chartered Institute of Marketing (CIM)CIMA')]</value>
      <webElementGuid>4b4c9023-af44-4735-a674-3c2ce52c9cda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
