<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Getting Started with OrangeHRMLearning _7c4cce</name>
   <tag></tag>
   <elementGuidId>69c4ce1f-ebfc-45b4-86ef-27967a925e7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[2]/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.orangehrm-card-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d33f0316-c8f0-4fc2-8f4b-0acbcb0acf44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>orangehrm-card-container</value>
      <webElementGuid>61a8d6aa-f52b-4821-ad52-702c03aee542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Getting Started with OrangeHRMLearning how to use a new application can be challenging. At OrangeHRM, we are committed to providing you with the necessary knowledge and skills required to fully utilize the application thereby allowing you to quickly and efficiently manage your HR processes.The following information repositories are available to help you understand the application:Customer SupportShould you experience any issues, please do not hesitate to contact us on  ossupport@orangehrm.com  We will be delighted to help.</value>
      <webElementGuid>157ec014-8fe4-4eb2-a655-8536b140fe30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;oxd-layout&quot;]/div[@class=&quot;oxd-layout-container&quot;]/div[@class=&quot;oxd-layout-context&quot;]/div[@class=&quot;orangehrm-background-container&quot;]/div[@class=&quot;orangehrm-card-container&quot;]</value>
      <webElementGuid>0371f0ca-aeae-4fb2-a00a-82e34f9d3ab5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[2]/div[2]/div/div</value>
      <webElementGuid>16ddc825-5a3f-4ed6-8b3f-6854443d6f80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div</value>
      <webElementGuid>1ba52d14-60e5-4bbc-99a4-eedefec65019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Getting Started with OrangeHRMLearning how to use a new application can be challenging. At OrangeHRM, we are committed to providing you with the necessary knowledge and skills required to fully utilize the application thereby allowing you to quickly and efficiently manage your HR processes.The following information repositories are available to help you understand the application:Customer SupportShould you experience any issues, please do not hesitate to contact us on  ossupport@orangehrm.com  We will be delighted to help.' or . = 'Getting Started with OrangeHRMLearning how to use a new application can be challenging. At OrangeHRM, we are committed to providing you with the necessary knowledge and skills required to fully utilize the application thereby allowing you to quickly and efficiently manage your HR processes.The following information repositories are available to help you understand the application:Customer SupportShould you experience any issues, please do not hesitate to contact us on  ossupport@orangehrm.com  We will be delighted to help.')]</value>
      <webElementGuid>d3cde865-9465-4635-8d23-809693df47a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
