<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Java</name>
   <tag></tag>
   <elementGuidId>10642ac7-8473-4ae0-ba1f-1c734463da2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.collapse.navbar-collapse.pull-right > ul.header-menu.clearfix > li.menu-item.menu-item-type-custom.menu-item-object-custom.menu-item-has-children.menu-item-7004 > ul.sub-menu > li.menu-item.menu-item-type-custom.menu-item-object-custom.menu-item-has-children.menu-item-6338 > ul.sub-menu > li.menu-item.menu-item-type-custom.menu-item-object-custom.menu-item-6342 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div[2]/div/div/div[3]/div[2]/div[2]/ul/li[6]/ul/li[2]/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5c94a402-db9a-4dea-98b2-4149092fff2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://youtube.com/playlist?list=PLNUKIBJDwfVusLwz-YrbwFfDAOkLHMIX7</value>
      <webElementGuid>0e60aeaf-0a42-47a7-a34b-7be1b5ebecc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Java</value>
      <webElementGuid>b4d10957-e1b9-4ee7-92c8-6c70d72dfac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header_default header_default&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-9 col-sm-9 col-sm-offset-0 hidden-xs hidden-sm&quot;]/div[@class=&quot;header_main_menu_wrapper clearfix&quot;]/div[@class=&quot;collapse navbar-collapse pull-right&quot;]/ul[@class=&quot;header-menu clearfix&quot;]/li[@class=&quot;menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-7004&quot;]/ul[@class=&quot;sub-menu&quot;]/li[@class=&quot;menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-6338&quot;]/ul[@class=&quot;sub-menu&quot;]/li[@class=&quot;menu-item menu-item-type-custom menu-item-object-custom menu-item-6342&quot;]/a[1]</value>
      <webElementGuid>a5e15c90-b0ce-475a-8c24-64c3c9ae76f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div[2]/div/div/div[3]/div[2]/div[2]/ul/li[6]/ul/li[2]/ul/li[4]/a</value>
      <webElementGuid>2e1f118a-ecea-4871-ad43-d03bcce1f7c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Java')])[4]</value>
      <webElementGuid>189f32b3-df89-4e47-bc0f-786228df4962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agile'])[2]/following::a[1]</value>
      <webElementGuid>59c2a930-511b-46a6-b828-6892b5fcacce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TestNG'])[4]/following::a[2]</value>
      <webElementGuid>72dbc8ea-946d-445f-8a3c-a07a19a05909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register For Demo'])[1]/preceding::a[1]</value>
      <webElementGuid>e10ad519-121c-4ea0-b57f-0372529a48d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://youtube.com/playlist?list=PLNUKIBJDwfVusLwz-YrbwFfDAOkLHMIX7')])[2]</value>
      <webElementGuid>2d427a9d-2570-4883-aa42-1a0a21fbb2dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[6]/ul/li[2]/ul/li[4]/a</value>
      <webElementGuid>00f5683c-7875-40f6-9c58-b75646489ba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://youtube.com/playlist?list=PLNUKIBJDwfVusLwz-YrbwFfDAOkLHMIX7' and (text() = 'Java' or . = 'Java')]</value>
      <webElementGuid>2f08b4be-ae64-4f6e-b821-60399c3e514c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
