<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Testimonials</name>
   <tag></tag>
   <elementGuidId>fda5b703-ca8e-4093-951f-46687e361782</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.collapse.navbar-collapse.pull-right > ul.header-menu.clearfix > li.menu-item.menu-item-type-custom.menu-item-object-custom.menu-item-has-children.menu-item-6374 > ul.sub-menu > li.menu-item.menu-item-type-post_type.menu-item-object-page.menu-item-5295 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div[2]/div/div/div[3]/div[2]/div[2]/ul/li[4]/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>96057427-06bd-4615-96c4-4a895d47b670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nxtgenaiacademy.com/testimonials/</value>
      <webElementGuid>62e5fdbb-bfa8-4581-8023-6ea30247bf9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Testimonials</value>
      <webElementGuid>eb3aa717-838d-4c9c-87c7-fff68f260373</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header_default header_default&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-9 col-sm-9 col-sm-offset-0 hidden-xs hidden-sm&quot;]/div[@class=&quot;header_main_menu_wrapper clearfix&quot;]/div[@class=&quot;collapse navbar-collapse pull-right&quot;]/ul[@class=&quot;header-menu clearfix&quot;]/li[@class=&quot;menu-item menu-item-type-custom menu-item-object-custom menu-item-has-children menu-item-6374&quot;]/ul[@class=&quot;sub-menu&quot;]/li[@class=&quot;menu-item menu-item-type-post_type menu-item-object-page menu-item-5295&quot;]/a[1]</value>
      <webElementGuid>2feeba56-423b-4836-9b2e-366b5a69c34d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div[2]/div/div/div[3]/div[2]/div[2]/ul/li[4]/ul/li[2]/a</value>
      <webElementGuid>da7e1540-9bed-49ef-9dd8-47d616ca5350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Testimonials')])[2]</value>
      <webElementGuid>b437fd6d-d4f8-4b65-ab47-98c39e76ef10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TechTalk'])[2]/following::a[1]</value>
      <webElementGuid>3a0fd1e3-5989-459e-a4cb-87dba239a253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About Me'])[2]/following::a[2]</value>
      <webElementGuid>a57d6d28-b585-4342-9909-106113618e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Python for Automation'])[2]/preceding::a[1]</value>
      <webElementGuid>1fda6965-bb26-47f2-b966-b8525725c636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Free Automation Courses'])[2]/preceding::a[2]</value>
      <webElementGuid>b6e38913-ce5d-480b-97fc-142f8c407934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://nxtgenaiacademy.com/testimonials/')])[2]</value>
      <webElementGuid>ae7da9cc-4e4c-41d2-baeb-b4c0a2b2c651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[4]/ul/li[2]/a</value>
      <webElementGuid>66a6e939-c00d-491a-baa2-9eb9a023cdd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nxtgenaiacademy.com/testimonials/' and (text() = 'Testimonials' or . = 'Testimonials')]</value>
      <webElementGuid>8a9a9cfc-c209-4685-9264-3f2f8fd1f5d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
