<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Postal  Zip Code_select2-selection sel_e0ab4c</name>
   <tag></tag>
   <elementGuidId>f18279f5-9b33-4500-b21a-22adbebcea70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.select2-selection.select2-selection--single</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='item-vfb-13']/div/span[6]/span/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e6138b15-0253-4750-9053-407dfa7eb338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>select2-selection select2-selection--single</value>
      <webElementGuid>2892d2e9-850b-4644-8d13-1e8b7edc0793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>71916090-ff29-4780-93dd-bec8f1104d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a5063bd6-5fd7-49ca-a846-c8419a3257b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2108158c-cc9b-45e7-a8db-b93d289e7424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b2532341-3150-4392-b959-d37928dc8033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f7bcfc52-1082-4462-bdff-41a452c4335a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>select2-vfb-13-country-container</value>
      <webElementGuid>e3314357-06f7-4a58-a5c3-c50b8c344109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>select2-vfb-13-country-container</value>
      <webElementGuid>7d7cee8e-7bd6-4d78-b5cb-e0546247fc71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>select2-vfb-13-country-results</value>
      <webElementGuid>61ffeb52-2cd7-4c04-b2b6-cdf896b23b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;item-vfb-13&quot;)/div[1]/span[@class=&quot;vfb-right&quot;]/span[@class=&quot;select2 select2-container select2-container--default select2-container--below select2-container--open&quot;]/span[@class=&quot;selection&quot;]/span[@class=&quot;select2-selection select2-selection--single&quot;]</value>
      <webElementGuid>fa5ae5b4-37a3-4617-b2ad-278c20feee56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='item-vfb-13']/div/span[6]/span/span/span</value>
      <webElementGuid>446ae320-9854-4de0-a0ce-9b5425659704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal / Zip Code'])[1]/following::span[4]</value>
      <webElementGuid>d51f3f0b-a6ba-4768-8bb7-64b2c1c53598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State / Province / Region'])[1]/following::span[5]</value>
      <webElementGuid>83a415fe-7f4a-4bbb-a38a-51c02a2bf860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/preceding::span[4]</value>
      <webElementGuid>6482c697-7f2d-4e4e-88c6-06a95ef3b579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[6]/span/span/span</value>
      <webElementGuid>82fa0cd5-52b5-44a6-89db-6a0ca8e936b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
