<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ul_Search_clearfix</name>
   <tag></tag>
   <elementGuidId>d33f7177-8eac-4cd3-b9fe-d09c57b8e71a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.clearfix</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='header']/div/div/div/div/div/ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>ul</value>
      <webElementGuid>684c67b5-e4d2-42a3-8fd9-0c32cefbb323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clearfix</value>
      <webElementGuid>03e9a168-067a-4d04-9132-73f37cc92197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header_top_bar&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;pull-right&quot;]/div[@class=&quot;header_top_bar_socs&quot;]/ul[@class=&quot;clearfix&quot;]</value>
      <webElementGuid>4dae9e81-f7a0-4ff9-b6ac-20a73996a59f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='header']/div/div/div/div/div/ul</value>
      <webElementGuid>f5047476-be34-480d-b897-6732cf7ee1df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/following::ul[1]</value>
      <webElementGuid>5d8ae022-90d9-424a-a460-ab02eece6789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle navigation'])[1]/preceding::ul[2]</value>
      <webElementGuid>e1238f2d-8442-4052-b24a-98ae9a100bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/preceding::ul[2]</value>
      <webElementGuid>d10f1ad3-3879-457b-923b-a5aef2be0543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul</value>
      <webElementGuid>8ae85463-9020-458a-8b73-542cee669acb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
